-- Auto-generated Neovim color configuration
-- This file is auto-generated by hyprstyle
-- Applies hyprstyle colors to override colorscheme highlights

local M = {}

function M.setup()
  -- Terminal colors (ANSI color codes 0-15)
  -- Used by terminal UI and colorschemes that respect terminal colors
  vim.g.terminal_color_0 = '${BG_DARK}'
  vim.g.terminal_color_8 = '${BG}'
  vim.g.terminal_color_1 = '${ERROR}'
  vim.g.terminal_color_9 = '${ERROR}'
  vim.g.terminal_color_2 = '${SUCCESS}'
  vim.g.terminal_color_10 = '${SUCCESS}'
  vim.g.terminal_color_3 = '${WARNING}'
  vim.g.terminal_color_11 = '${WARNING}'
  vim.g.terminal_color_4 = '${PRIMARY}'
  vim.g.terminal_color_12 = '${PRIMARY}'
  vim.g.terminal_color_5 = '${ACCENT}'
  vim.g.terminal_color_13 = '${ACCENT}'
  vim.g.terminal_color_6 = '${SECONDARY}'
  vim.g.terminal_color_14 = '${SECONDARY}'
  vim.g.terminal_color_7 = '${TEXT}'
  vim.g.terminal_color_15 = '${TEXT}'

  -- Ensure true color support is enabled
  vim.opt.termguicolors = true

  -- Apply hyprstyle colors to editor highlights
  -- This overrides the colorscheme to use our extracted colors
  local hl = vim.api.nvim_set_hl

  -- Basic UI colors
  hl(0, "Normal", { fg = "${TEXT}", bg = "${BG}" })
  hl(0, "NormalNC", { fg = "${TEXT}", bg = "${BG}" })
  hl(0, "NormalFloat", { fg = "${TEXT}", bg = "${BG}" })

  -- Cursor and selection
  hl(0, "Cursor", { fg = "${BG}", bg = "${TEXT}" })
  hl(0, "CursorLine", { bg = "${CURSORLINE}" })
  hl(0, "CursorLineNr", { fg = "${PRIMARY}", bold = true })
  hl(0, "Visual", { fg = "${BG}", bg = "${ACCENT}" })

  -- Line numbers and signs
  hl(0, "LineNr", { fg = "${BG_LIGHT}" })
  hl(0, "SignColumn", { fg = "${BG_LIGHT}", bg = "${BG}" })

  -- Syntax highlighting
  hl(0, "Statement", { fg = "${PRIMARY}", bold = true })
  hl(0, "String", { fg = "${SUCCESS}" })
  hl(0, "Comment", { fg = "${BG_LIGHT}", italic = true })
  hl(0, "Type", { fg = "${SECONDARY}" })
  hl(0, "Function", { fg = "${PRIMARY}" })
  hl(0, "Keyword", { fg = "${PRIMARY}", bold = true })
  hl(0, "Constant", { fg = "${ACCENT}" })

  -- Error, Warning, Info
  hl(0, "Error", { fg = "${ERROR}", bold = true })
  hl(0, "Warning", { fg = "${WARNING}", bold = true })
  hl(0, "DiagnosticError", { fg = "${ERROR}" })
  hl(0, "DiagnosticWarn", { fg = "${WARNING}" })
  hl(0, "DiagnosticInfo", { fg = "${PRIMARY}" })
  hl(0, "DiagnosticHint", { fg = "${SECONDARY}" })

  -- Search and diff
  hl(0, "Search", { bg = "${WARNING}" })
  hl(0, "IncSearch", { bg = "${ACCENT}" })
  hl(0, "DiffAdd", { bg = "${SUCCESS}" })
  hl(0, "DiffDelete", { bg = "${ERROR}" })
  hl(0, "DiffChange", { bg = "${PRIMARY}" })

  -- Menu and completion
  hl(0, "Pmenu", { fg = "${TEXT}", bg = "${BG_LIGHT}" })
  hl(0, "PmenuSel", { fg = "${BG}", bg = "${ACCENT}", bold = true })
  hl(0, "PmenuBorder", { fg = "${ACCENT}" })

  -- nvim-tree colors (match Neovim theme)
  hl(0, "NvimTreeNormal", { fg = "${TEXT}", bg = "${BG}" })
  hl(0, "NvimTreeNormalNC", { fg = "${TEXT}", bg = "${BG}" })
  hl(0, "NvimTreeRootFolder", { fg = "${PRIMARY}", bold = true })
  hl(0, "NvimTreeFolderName", { fg = "${PRIMARY}" })
  hl(0, "NvimTreeFolderIcon", { fg = "${PRIMARY}" })
  hl(0, "NvimTreeOpenedFolderName", { fg = "${SUCCESS}", bold = true })
  hl(0, "NvimTreeEmptyFolderName", { fg = "${BG_LIGHT}" })
  hl(0, "NvimTreeFileName", { fg = "${TEXT}" })
  hl(0, "NvimTreeFileIcon", { fg = "${PRIMARY}" })
  hl(0, "NvimTreeExecFile", { fg = "${SUCCESS}" })
  hl(0, "NvimTreeSymlink", { fg = "${WARNING}" })
  hl(0, "NvimTreeGitDirty", { fg = "${WARNING}" })
  hl(0, "NvimTreeGitStaged", { fg = "${SUCCESS}" })
  hl(0, "NvimTreeGitMerge", { fg = "${PRIMARY}" })
  hl(0, "NvimTreeGitRenamed", { fg = "${WARNING}" })
  hl(0, "NvimTreeGitNew", { fg = "${SUCCESS}" })
  hl(0, "NvimTreeGitDeleted", { fg = "${ERROR}" })
  hl(0, "NvimTreeSignColumn", { bg = "${BG}" })
  hl(0, "NvimTreeStatusLine", { fg = "${PRIMARY}", bg = "${CURSORLINE}" })
  hl(0, "NvimTreeStatusLineNC", { fg = "${BG_LIGHT}", bg = "${CURSORLINE}" })
  hl(0, "NvimTreeCursorLine", { bg = "${CURSORLINE}" })

  -- Lualine statusline colors (match Neovim theme)
  hl(0, "lualine_a_normal", { fg = "${BG}", bg = "${PRIMARY}", bold = true })
  hl(0, "lualine_b_normal", { fg = "${PRIMARY}", bg = "${CURSORLINE}" })
  hl(0, "lualine_c_normal", { fg = "${TEXT}", bg = "${BG}" })
  hl(0, "lualine_x_normal", { fg = "${TEXT}", bg = "${BG}" })
  hl(0, "lualine_y_normal", { fg = "${PRIMARY}", bg = "${CURSORLINE}" })
  hl(0, "lualine_z_normal", { fg = "${BG}", bg = "${PRIMARY}", bold = true })

  hl(0, "lualine_a_insert", { fg = "${BG}", bg = "${SUCCESS}", bold = true })
  hl(0, "lualine_a_visual", { fg = "${BG}", bg = "${WARNING}", bold = true })
  hl(0, "lualine_a_replace", { fg = "${BG}", bg = "${ERROR}", bold = true })
  hl(0, "lualine_a_command", { fg = "${BG}", bg = "${PRIMARY}", bold = true })

  hl(0, "lualine_a_inactive", { fg = "${BG_LIGHT}", bg = "${CURSORLINE}" })
  hl(0, "lualine_b_inactive", { fg = "${BG_LIGHT}", bg = "${CURSORLINE}" })
  hl(0, "lualine_c_inactive", { fg = "${BG_LIGHT}", bg = "${BG}" })
end

return M
